//
// Created by Mahmud Jego on 3/6/21.
//
#include <string>
#include <map>

const std::map<std::string, std::string>& initMimeType(std::map<std::string, std::string>& mimeTypes)
{
//	if (mimeTypes.empty())
	{
		mimeTypes[".php"] = "text/html";
		mimeTypes[".bmp"] = "image/bmp";
		mimeTypes[".cgm"] = "image/cgm";
		mimeTypes[".g3"] = "image/g3fax";
		mimeTypes[".gif"] = "image/gif";
		mimeTypes[".ief"] = "image/ief";
		mimeTypes[".jpeg"] = "image/jpeg";
		mimeTypes[".jpg"] = "image/jpeg";
		mimeTypes[".ktx"] = "image/ktx";
		mimeTypes[".pjpeg"] = "image/pjpeg";
		mimeTypes[".png"] = "image/png";
		mimeTypes[".btif"] = "image/prs.btif";
		mimeTypes[".svg"] = "image/svg+xml";
		mimeTypes[".tiff"] = "image/tiff";
		mimeTypes[".psd"] = "image/vnd.adobe.photoshop";
		mimeTypes[".uvi"] = "image/vnd.dece.graphic";
		mimeTypes[".djvu"] = "image/vnd.djvu";
		mimeTypes[".sub"] = "image/vnd.dvb.subtitle";
		mimeTypes[".dwg"] = "image/vnd.dwg";
		mimeTypes[".dxf"] = "image/vnd.dxf";
		mimeTypes[".fbs"] = "image/vnd.fastbidsheet";
		mimeTypes[".fpx"] = "image/vnd.fpx";
		mimeTypes[".fst"] = "image/vnd.fst";
		mimeTypes[".mmr"] = "image/vnd.fujixerox.edmics-mmr";
		mimeTypes[".rlc"] = "image/vnd.fujixerox.edmics-rlc";
		mimeTypes[".mdi"] = "image/vnd.ms-modi";
		mimeTypes[".npx"] = "image/vnd.net-fpx";
		mimeTypes[".wbmp"] = "image/vnd.wap.wbmp";
		mimeTypes[".xif"] = "image/vnd.xiff";
		mimeTypes[".webp"] = "image/webp";
		mimeTypes[".jpeg"] = "image/x-citrix-jpeg";
		mimeTypes[".png"] = "image/x-citrix-png";
		mimeTypes[".ras"] = "image/x-cmu-raster";
		mimeTypes[".cmx"] = "image/x-cmx";
		mimeTypes[".fh"] = "image/x-freehand";
		mimeTypes[".ico"] = "image/x-icon";
		mimeTypes[".pcx"] = "image/x-pcx";
		mimeTypes[".pic"] = "image/x-pict";
		mimeTypes[".png"] = "image/x-png";
		mimeTypes[".pnm"] = "image/x-portable-anymap";
		mimeTypes[".pbm"] = "image/x-portable-bitmap";
		mimeTypes[".pgm"] = "image/x-portable-graymap";
		mimeTypes[".ppm"] = "image/x-portable-pixmap";
		mimeTypes[".rgb"] = "image/x-rgb";
		mimeTypes[".xbm"] = "image/x-xbitmap";
		mimeTypes[".xpm"] = "image/x-xpixmap";
		mimeTypes[".xwd"] = "image/x-xwindowdump";
		mimeTypes[".adp"] = "audio/adpcm";
		mimeTypes[".au"] = "audio/basic";
		mimeTypes[".mid"] = "audio/midi";
		mimeTypes[".mp4a"] = "audio/mp4";
		mimeTypes[".mpga"] = "audio/mpeg";
		mimeTypes[".oga"] = "audio/ogg";
		mimeTypes[".uva"] = "audio/vnd.dece.audio";
		mimeTypes[".eol"] = "audio/vnd.digital-winds";
		mimeTypes[".dra"] = "audio/vnd.dra";
		mimeTypes[".dts"] = "audio/vnd.dts";
		mimeTypes[".dtshd"] = "audio/vnd.dts.hd";
		mimeTypes[".lvp"] = "audio/vnd.lucent.voice";
		mimeTypes[".pya"] = "audio/vnd.ms-playready.media.pya";
		mimeTypes[".ecelp4800"] = "audio/vnd.nuera.ecelp4800";
		mimeTypes[".ecelp7470"] = "audio/vnd.nuera.ecelp7470";
		mimeTypes[".ecelp9600"] = "audio/vnd.nuera.ecelp9600";
		mimeTypes[".rip"] = "audio/vnd.rip";
		mimeTypes[".weba"] = "audio/webm";
		mimeTypes[".aac"] = "audio/x-aac";
		mimeTypes[".aif"] = "audio/x-aiff";
		mimeTypes[".m3u"] = "audio/x-mpegurl";
		mimeTypes[".wax"] = "audio/x-ms-wax";
		mimeTypes[".wma"] = "audio/x-ms-wma";
		mimeTypes[".ram"] = "audio/x-pn-realaudio";
		mimeTypes[".rmp"] = "audio/x-pn-realaudio-plugin";
		mimeTypes[".wav"] = "audio/x-wav";
		mimeTypes[".3gp"] = "video/3gpp";
		mimeTypes[".3g2"] = "video/3gpp2";
		mimeTypes[".h261"] = "video/h261";
		mimeTypes[".h263"] = "video/h263";
		mimeTypes[".h264"] = "video/h264";
		mimeTypes[".jpgv"] = "video/jpeg";
		mimeTypes[".jpm"] = "video/jpm";
		mimeTypes[".mj2"] = "video/mj2";
		mimeTypes[".mp4"] = "video/mp4";
		mimeTypes[".mpeg"] = "video/mpeg";
		mimeTypes[".ogv"] = "video/ogg";
		mimeTypes[".qt"] = "video/quicktime";
		mimeTypes[".uvh"] = "video/vnd.dece.hd";
		mimeTypes[".uvm"] = "video/vnd.dece.mobile";
		mimeTypes[".uvp"] = "video/vnd.dece.pd";
		mimeTypes[".uvs"] = "video/vnd.dece.sd";
		mimeTypes[".uvv"] = "video/vnd.dece.video";
		mimeTypes[".fvt"] = "video/vnd.fvt";
		mimeTypes[".mxu"] = "video/vnd.mpegurl";
		mimeTypes[".pyv"] = "video/vnd.ms-playready.media.pyv";
		mimeTypes[".uvu"] = "video/vnd.uvvu.mp4";
		mimeTypes[".viv"] = "video/vnd.vivo";
		mimeTypes[".webm"] = "video/webm";
		mimeTypes[".f4v"] = "video/x-f4v";
		mimeTypes[".fli"] = "video/x-fli";
		mimeTypes[".flv"] = "video/x-flv";
		mimeTypes[".m4v"] = "video/x-m4v";
		mimeTypes[".asf"] = "video/x-ms-asf";
		mimeTypes[".wm"] = "video/x-ms-wm";
		mimeTypes[".wmv"] = "video/x-ms-wmv";
		mimeTypes[".wmx"] = "video/x-ms-wmx";
		mimeTypes[".wvx"] = "video/x-ms-wvx";
		mimeTypes[".avi"] = "video/x-msvideo";
		mimeTypes[".movie"] = "video/x-sgi-movie";
		mimeTypes[".ics"] = "text/calendar";
		mimeTypes[".css"] = "text/css";
		mimeTypes[".csv"] = "text/csv";
		mimeTypes[".html"] = "text/html";
		mimeTypes[".n3"] = "text/n3";
		mimeTypes[".txt"] = "text/plain";
		mimeTypes[".par"] = "text/plain-bas";
		mimeTypes[".dsc"] = "text/prs.lines.tag";
		mimeTypes[".rtx"] = "text/richtext";
		mimeTypes[".sgml"] = "text/sgml";
		mimeTypes[".tsv"] = "text/tab-separated-values";
		mimeTypes[".t"] = "text/troff";
		mimeTypes[".ttl"] = "text/turtle";
		mimeTypes[".uri"] = "text/uri-list";
		mimeTypes[".curl"] = "text/vnd.curl";
		mimeTypes[".dcurl"] = "text/vnd.curl.dcurl";
		mimeTypes[".mcurl"] = "text/vnd.curl.mcurl";
		mimeTypes[".scurl"] = "text/vnd.curl.scurl";
		mimeTypes[".fly"] = "text/vnd.fly";
		mimeTypes[".flx"] = "text/vnd.fmi.flexstor";
		mimeTypes[".gv"] = "text/vnd.graphviz";
		mimeTypes["3dml"] = "text/vnd.in3d.3dml	";
		mimeTypes[".spot"] = "text/vnd.in3d.spot";
		mimeTypes[".jad"] = "text/vnd.sun.j2me.app-descriptor";
		mimeTypes[".wml"] = "text/vnd.wap.wml";
		mimeTypes[".wmls"] = "text/vnd.wap.wmlscript";
		mimeTypes[".s"] = "text/x-asm";
		mimeTypes[".c"] = "text/x-c";
		mimeTypes[".f"] = "text/x-fortran";
		mimeTypes[".java"] = "text/x-java-source";
		mimeTypes[".p"] = "text/x-pascal";
		mimeTypes[".etx"] = "text/x-setext";
		mimeTypes[".uu"] = "text/x-uuencode";
		mimeTypes[".vcs"] = "text/x-vcalendar";
		mimeTypes[".vcf"] = "text/x-vcard";
		mimeTypes[".yaml"] = "text/yaml";

		mimeTypes["N/A"] = "application/andrew-inset";
		mimeTypes[".aw"] = "application/applixware"; //	Applixware
		mimeTypes[".atom"] = "application/atom+xml"; //
		mimeTypes[".xml"] = "application/atom+xml"; //	Atom Syndication Format
		mimeTypes[".atomcat"] = "application/atomcat+xml"; //	Atom Publishing Protocol
		mimeTypes[".atomsvc"] = "application/atomsvc+xml"; //	Atom Publishing Protocol Service Document
		mimeTypes[".ccxml"] = "application/ccxml+xml"; //	Voice Browser Call Control
		mimeTypes[".cdmia"] = "application/cdmi-capability"; //	Cloud Data Management Interface (CDMI) - Capability
		mimeTypes[".cdmic"] = "application/cdmi-container"; //	Cloud Data Management Interface (CDMI) - Contaimer
		mimeTypes[".cdmid"] = "application/cdmi-domain"; //	Cloud Data Management Interface (CDMI) - Domain
		mimeTypes[".cdmio"] = "application/cdmi-object"; //	Cloud Data Management Interface (CDMI) - Object
		mimeTypes[".cdmiq"] = "application/cdmi-queue"; //	Cloud Data Management Interface (CDMI) - Queue
		mimeTypes[".cu"] = "application/cu-seeme"; //	CU-SeeMe
		mimeTypes[".davmount"] = "application/davmount+xml"; //	Web Distributed Authoring and Versioning
		mimeTypes[".dssc"] = "application/dssc+der"; //	Data Structure for the Security Suitability of Cryptographic Algorithms
		mimeTypes[".xdssc"] = "application/dssc+xml"; //	Data Structure for the Security Suitability of Cryptographic Algorithms
		mimeTypes[".es"] = "application/ecmascript"; //	ECMAScript
		mimeTypes[".emma"] = "application/emma+xml"; //	Extensible MultiModal Annotation
		mimeTypes[".epub"] = "application/epub+zip"; //	Electronic Publication
		mimeTypes[".exi"] = "application/exi"; //	Efficient XML Interchange
		mimeTypes[".pfr"] = "application/font-tdpfr"; //	Portable Font Resource
		mimeTypes[".stk"] = "application/hyperstudio"; //	Hyperstudio
		mimeTypes[".ipfix"] = "application/ipfix"; //	Internet Protocol Flow Information Export
		mimeTypes[".jar"] = "application/java-archive"; //	Java Archive
		mimeTypes[".ser"] = "application/java-serialized-object"; //	Java Serialized Object
		mimeTypes[".class"] = "application/java-vm"; //	Java Bytecode File
		mimeTypes[".js"] = "application/javascript"; //	JavaScript
		mimeTypes[".json"] = "application/json"; //	JavaScript Object Notation (JSON)
		mimeTypes[".hqx"] = "application/mac-binhex40"; //	Macintosh BinHex 4,0
		mimeTypes[".cpt"] = "application/mac-compactpro"; //	Compact Pro
		mimeTypes[".mads"] = "application/mads+xml"; //	Metadata Authority Description Schema
		mimeTypes[".mrc"] = "application/marc"; //	MARC Formats
		mimeTypes[".mrcx"] = "application/marcxml+xml"; //	MARC21 XML Schema
		mimeTypes[".ma"] = "application/mathematica"; //	Mathematica Notebooks
		mimeTypes[".mathml"] = "application/mathml+xml"; //	Mathematical Markup Language
		mimeTypes[".mbox"] = "application/mbox"; //	Mbox database files
		mimeTypes[".mscml"] = "application/mediaservercontrol+xml"; //	Media Server Control Markup Language
		mimeTypes[".meta4"] = "application/metalink4+xml"; //	Metalink
		mimeTypes[".mets"] = "application/mets+xml"; //	Metadata Encoding and Transmission Standard
		mimeTypes[".mods"] = "application/mods+xml"; //	Metadata Object Description Schema
		mimeTypes[".m21"] = "application/mp21"; //	MPEG-21
		mimeTypes[".mp4"] = "application/mp4"; //	MPEG4
		mimeTypes[".doc"] = "application/msword"; //	Microsoft Word
		mimeTypes[".mxf"] = "application/mxf"; //	Material Exchange Format
		mimeTypes[".bin"] = "application/octet-stream"; //	Binary Data
		mimeTypes[".oda"] = "application/oda"; //	Office Document Architecture
		mimeTypes[".opf"] = "application/oebps-package+xml"; //	Open eBook Publication Structure
		mimeTypes[".ogx"] = "application/ogg"; //	Ogg
		mimeTypes[".onetoc"] = "application/onenote"; //	Microsoft OneNote
		mimeTypes[".xer"] = "application/patch-ops-error+xml"; //	XML Patch Framework
		mimeTypes[".pdf"] = "application/pdf"; //	Adobe Portable Document Format
		mimeTypes[".pgp"] = "application/pgp-encrypted"; //	Pretty Good Privacy
		mimeTypes[".pgp"] = "application/pgp-signature"; //	Pretty Good Privacy - Signature
		mimeTypes[".prf"] = "application/pics-rules"; //	PICSRules
		mimeTypes[".p10"] = "application/pkcs10"; //	PKCS #10 - Certification Request Standard
		mimeTypes[".p7m"] = "application/pkcs7-mime"; //	PKCS #7 - Cryptographic Message Syntax Standard
		mimeTypes[".p7s"] = "application/pkcs7-signature"; //	PKCS #7 - Cryptographic Message Syntax Standard
		mimeTypes[".p8"] = "application/pkcs8"; //	PKCS #8 - Private-Key Information Syntax Standard
		mimeTypes[".ac"] = "application/pkix-attr-cert"; //	Attribute Certificate
		mimeTypes[".cer"] = "application/pkix-cert"; //	Internet Public Key Infrastructure - Certificate
		mimeTypes[".crl"] = "application/pkix-crl"; //	Internet Public Key Infrastructure - Certificate Revocation Lists
		mimeTypes[".pkipath"] = "application/pkix-pkipath"; //	Internet Public Key Infrastructure - Certification Path
		mimeTypes[".pki"] = "application/pkixcmp"; //	Internet Public Key Infrastructure - Certificate Management Protocole
		mimeTypes[".pls"] = "application/pls+xml"; //	Pronunciation Lexicon Specification
		mimeTypes[".ai"] = "application/postscript"; //	PostScript
		mimeTypes[".cww"] = "application/prs.cww"; //	CU-Writer
		mimeTypes[".pskcxml"] = "application/pskc+xml"; //	Portable Symmetric Key Container
		mimeTypes[".rdf"] = "application/rdf+xml"; //	Resource Description Framework
		mimeTypes[".rif"] = "application/reginfo+xml"; //	IMS Networks
		mimeTypes[".rnc"] = "application/relax-ng-compact-syntax"; //	Relax NG Compact Syntax
		mimeTypes[".rld"] = "application/resource-lists-diff+xml"; //	XML Resource Lists Diff
		mimeTypes[".rl"] = "application/resource-lists+xml"; //	XML Resource Lists
		mimeTypes[".rs"] = "application/rls-services+xml"; //	XML Resource Lists
		mimeTypes[".rsd"] = "application/rsd+xml"; //	Really Simple Discovery
		mimeTypes[".rss"] = "application/rss+xml"; //	RSS - Really Simple Syndication
		mimeTypes[".xml"] = "application/rtf"; //	Rich Text Format
		mimeTypes[".rtf"] = "application/sbml+xml"; //	Systems Biology Markup Language
		mimeTypes[".sbml"] = "application/scvp-cv-request"; //	Server-Based Certificate Validation Protocol - Validation Request
		mimeTypes[".scq"] = "application/scvp-cv-response"; //	Server-Based Certificate Validation Protocol - Validation king_Response
		mimeTypes[".scs"] = "application/scvp-vp-request"; //	Server-Based Certificate Validation Protocol - Validation Policies - Request
		mimeTypes[".spq"] = "application/scvp-vp-response"; //	Server-Based Certificate Validation Protocol - Validation Policies - king_Response
		mimeTypes[".spp"] = "application/sdp"; //	Session Description Protocol
		mimeTypes[".sdp"] = "application/set-payment-initiation"; //	Secure Electronic Transaction - Payment
		mimeTypes[".setpay"] = "application/set-registration-initiation"; //	Secure Electronic Transaction - Registration
		mimeTypes[".setreg"] = "application/shf+xml"; //	S Hexdump Format
		mimeTypes[".shf"] = "application/smil+xml"; //	Synchronized Multimedia Integration Language
		mimeTypes[".smi"] = "application/sparql-query"; //	SPARQL - Query
		mimeTypes[".rq"] = "application/sparql-results+xml"; //	SPARQL - Results
		mimeTypes[".srx"] = "application/srgs"; //	Speech Recognition Grammar Specification
		mimeTypes[".gram"] = "application/srgs+xml"; //	Speech Recognition Grammar Specification - XML
		mimeTypes[".grxml"] = "application/sru+xml"; //	Search/Retrieve via URL king_Response Format
		mimeTypes[".sru"] = "application/ssml+xml"; //	Speech Synthesis Markup Language
		mimeTypes[".ssml"] = "application/tei+xml"; //	Text Encoding and Interchange
		mimeTypes[".tei"] = "application/thraud+xml"; //	Sharing Transaction Fraud Data
		mimeTypes[".tfi"] = "application/timestamped-data"; //	Time Stamped Data Envelope
		mimeTypes[".plb"] = "application/vnd.3gpp.pic-bw-large"; //	3rd Generation Partnership Project - Pic Large
		mimeTypes[".psb"] = "application/vnd.3gpp.pic-bw-small"; //	3rd Generation Partnership Project - Pic Small
		mimeTypes[".pvb"] = "application/vnd.3gpp.pic-bw-var"; //	3rd Generation Partnership Project - Pic Var
		mimeTypes[".tcap"] = "application/vnd.3gpp2.tcap"; //	3rd Generation Partnership Project - Transaction Capabilities Application Part
		mimeTypes[".pwn"] = "application/vnd.3m.post-it-notes"; //	3M Post It Notes
		mimeTypes[".aso"] = "application/vnd.accpac.simply.aso"; //	Simply Accounting
		mimeTypes[".imp"] = "application/vnd.accpac.simply.imp"; //	Simply Accounting - Data Import
		mimeTypes[".acu"] = "application/vnd.acucobol"; //	ACU Cobol
		mimeTypes[".atc"] = "application/vnd.acucorp"; //	ACU Cobol
		mimeTypes[".air"] = "application/vnd.adobe.air-application-installer-package+zip"; //	Adobe AIR Application
		mimeTypes[".fxp"] = "application/vnd.adobe.fxp"; //	Adobe Flex Project
		mimeTypes[".xdp"] = "application/vnd.adobe.xdp+xml"; //	Adobe XML Data Package
		mimeTypes[".xfdf"] = "application/vnd.adobe.xfdf"; //	Adobe XML Forms Data Format
		mimeTypes[".ahead"] = "application/vnd.ahead.space"; //	Ahead AIR Application
		mimeTypes[".azf"] = "application/vnd.airzip.filesecure.azf"; //	AirZip FileSECURE
		mimeTypes[".azs"] = "application/vnd.airzip.filesecure.azs"; //	AirZip FileSECURE
		mimeTypes[".azw"] = "application/vnd.amazon.ebook"; //	Amazon Kindle eBook format
		mimeTypes[".acc"] = "application/vnd.americandynamics.acc"; //	Active Content Compression
		mimeTypes[".ami"] = "application/vnd.amiga.ami"; //	AmigaDE
		mimeTypes[".apk"] = "application/vnd.android.package-archive"; //	Android Package Archive
		mimeTypes[".cii"] = "application/vnd.anser-web-certificate-issue-initiation"; //	ANSER-WEB Terminal Client - Certificate Issue
		mimeTypes[".fti"] = "application/vnd.anser-web-funds-transfer-initiation"; //	ANSER-WEB Terminal Client - Web Funds Transfer
		mimeTypes[".atx"] = "application/vnd.antix.game-component"; //	Antix Game Player
		mimeTypes[".mpkg"] = "application/vnd.apple.installer+xml"; //	Apple Installer Package
		mimeTypes[".m3u8"] = "application/vnd.apple.mpegurl"; //	Multimedia Playlist Unicode
		mimeTypes[".swi"] = "application/vnd.aristanetworks.swi"; //	Arista Networks Software Image
		mimeTypes[".aep"] = "application/vnd.audiograph"; //	Audiograph
		mimeTypes[".mpm"] = "application/vnd.blueice.multipass"; //	Blueice Research Multipass
		mimeTypes[".bmi"] = "application/vnd.bmi"; //	BMI Drawing Data Interchange
		mimeTypes[".rep"] = "application/vnd.businessobjects"; //	BusinessObjects
		mimeTypes[".cdxml"] = "application/vnd.chemdraw+xml"; //	CambridgeSoft Chem Draw
		mimeTypes[".mmd"] = "application/vnd.chipnuts.karaoke-mmd"; //	Karaoke on Chipnuts Chipsets
		mimeTypes[".cdy"] = "application/vnd.cinderella"; //	Interactive Geometry Software Cinderella
		mimeTypes[".cla"] = "application/vnd.claymore"; //	Claymore Data Files
		mimeTypes[".rp9"] = "application/vnd.cloanto.rp9"; //	RetroPlatform Player
		mimeTypes[".c4g"] = "application/vnd.clonk.c4group"; //	Clonk Game
		mimeTypes[".c11amc"] = "application/vnd.cluetrust.cartomobile-config"; //	ClueTrust CartoMobile - Config
		mimeTypes[".c11amz"] = "application/vnd.cluetrust.cartomobile-config-pkg"; //	ClueTrust CartoMobile - Config Package
		mimeTypes[".csp"] = "application/vnd.commonspace"; //	Sixth Floor Media - CommonSpace
		mimeTypes[".cdbcmsg"] = "application/vnd.contact.cmsg"; //	CIM Database
		mimeTypes[".cmc"] = "application/vnd.cosmocaller"; //	CosmoCaller
		mimeTypes[".clkx"] = "application/vnd.crick.clicker"; //	CrickSoftware - Clicker
		mimeTypes[".clkk"] = "application/vnd.crick.clicker.keyboard"; //	CrickSoftware - Clicker - Keyboard
		mimeTypes[".clkp"] = "application/vnd.crick.clicker.palette"; //	CrickSoftware - Clicker - Palette
		mimeTypes[".clkt"] = "application/vnd.crick.clicker.template"; //	CrickSoftware - Clicker - Template
		mimeTypes[".clkw"] = "application/vnd.crick.clicker.wordbank"; //	CrickSoftware - Clicker - Wordbank
		mimeTypes[".wbs"] = "application/vnd.criticaltools.wbs+xml"; //	Critical Tools - PERT Chart EXPERT
		mimeTypes[".pml"] = "application/vnd.ctc-posml"; //	PosML
		mimeTypes[".ppd"] = "application/vnd.cups-ppd"; //	Adobe PostScript Printer Description File Format
		mimeTypes[".car"] = "application/vnd.curl.car"; //	CURL Applet
		mimeTypes[".pcurl"] = "application/vnd.curl.pcurl"; //	CURL Applet
		mimeTypes[".rdz"] = "application/vnd.data-vision.rdz"; //	RemoteDocs R-Viewer
		mimeTypes[".fe_launch"] = "application/vnd.denovo.fcselayout-link"; //	FCS Express Layout Link
		mimeTypes[".dna"] = "application/vnd.dna"; //	New Moon Liftoff/DNA
		mimeTypes[".mlp"] = "application/vnd.dolby.mlp"; //	Dolby Meridian Lossless Packing
		mimeTypes[".dpg"] = "application/vnd.dpgraph"; //	DPGraph
		mimeTypes[".dfac"] = "application/vnd.dreamfactory"; //	DreamFactory
		mimeTypes[".ait"] = "application/vnd.dvb.ait"; //	Digital Video Broadcasting
		mimeTypes[".svc"] = "application/vnd.dvb.service"; //	Digital Video Broadcasting
		mimeTypes[".geo"] = "application/vnd.dynageo"; //	DynaGeo
		mimeTypes[".mag"] = "application/vnd.ecowin.chart"; //	EcoWin Chart
		mimeTypes[".nml"] = "application/vnd.enliven"; //	Enliven Viewer
		mimeTypes[".esf"] = "application/vnd.epson.esf"; //	QUASS Stream Player
		mimeTypes[".msf"] = "application/vnd.epson.msf"; //	QUASS Stream Player
		mimeTypes[".qam"] = "application/vnd.epson.quickanime"; //	QuickAnime Player
		mimeTypes[".slt"] = "application/vnd.epson.salt"; //	SimpleAnimeLite Player
		mimeTypes[".ssf"] = "application/vnd.epson.ssf"; //	QUASS Stream Player
		mimeTypes[".es3"] = "application/vnd.eszigno3+xml"; //	MICROSEC e-Szign¢
		mimeTypes[".ez2"] = "application/vnd.ezpix-album"; //	EZPix Secure Photo Album
		mimeTypes[".ez3"] = "application/vnd.ezpix-package"; //	EZPix Secure Photo Album
		mimeTypes[".fdf"] = "application/vnd.fdf"; //	Forms Data Format
		mimeTypes[".seed"] = "application/vnd.fdsn.seed"; //	Digital Siesmograph Networks - SEED Datafiles
		mimeTypes[".gph"] = "application/vnd.flographit"; //	NpGraphIt
		mimeTypes[".ftc"] = "application/vnd.fluxtime.clip"; //	FluxTime Clip
		mimeTypes[".fm"] = "application/vnd.framemaker"; //	FrameMaker Normal Format
		mimeTypes[".fnc"] = "application/vnd.frogans.fnc"; //	Frogans Player
		mimeTypes[".ltf"] = "application/vnd.frogans.ltf"; //	Frogans Player
		mimeTypes[".fsc"] = "application/vnd.fsc.weblaunch"; //	Friendly Software Corporation
		mimeTypes[".oas"] = "application/vnd.fujitsu.oasys"; //	Fujitsu Oasys
		mimeTypes[".oa2"] = "application/vnd.fujitsu.oasys2"; //	Fujitsu Oasys
		mimeTypes[".oa3"] = "application/vnd.fujitsu.oasys3"; //	Fujitsu Oasys
		mimeTypes[".fg5"] = "application/vnd.fujitsu.oasysgp"; //	Fujitsu Oasys
		mimeTypes[".bh2"] = "application/vnd.fujitsu.oasysprs"; //	Fujitsu Oasys
		mimeTypes[".ddd"] = "application/vnd.fujixerox.ddd"; //	Fujitsu - Xerox 2D CAD Data
		mimeTypes[".xdw"] = "application/vnd.fujixerox.docuworks"; //	Fujitsu - Xerox DocuWorks
		mimeTypes[".xbd"] = "application/vnd.fujixerox.docuworks.binder"; //	Fujitsu - Xerox DocuWorks Binder
		mimeTypes[".fzs"] = "application/vnd.fuzzysheet"; //	FuzzySheet
		mimeTypes[".txd"] = "application/vnd.genomatix.tuxedo"; //	Genomatix Tuxedo Framework
		mimeTypes[".ggb"] = "application/vnd.geogebra.file"; //	GeoGebra
		mimeTypes[".ggt"] = "application/vnd.geogebra.tool"; //	GeoGebra
		mimeTypes[".gex"] = "application/vnd.geometry-explorer"; //	GeoMetry Explorer
		mimeTypes[".gxt"] = "application/vnd.geonext"; //	GEONExT and JSXGraph
		mimeTypes[".g2w"] = "application/vnd.geoplan"; //	GeoplanW
		mimeTypes[".g3w"] = "application/vnd.geospace"; //	GeospacW
		mimeTypes[".gmx"] = "application/vnd.gmx"; //	GameMaker ActiveX
		mimeTypes[".kml"] = "application/vnd.google-earth.kml+xml"; //	Google Earth - KML
		mimeTypes[".kmz"] = "application/vnd.google-earth.kmz"; //	Google Earth - Zipped KML
		mimeTypes[".gqf"] = "application/vnd.grafeq"; //	GrafEq
		mimeTypes[".gac"] = "application/vnd.groove-account"; //	Groove - Account
		mimeTypes[".ghf"] = "application/vnd.groove-help"; //	Groove - Help
		mimeTypes[".gim"] = "application/vnd.groove-identity-message"; //	Groove - Identity Message
		mimeTypes[".grv"] = "application/vnd.groove-injector"; //	Groove - Injector
		mimeTypes[".gtm"] = "application/vnd.groove-tool-message"; //	Groove - Tool Message
		mimeTypes[".tpl"] = "application/vnd.groove-tool-template"; //	Groove - Tool Template
		mimeTypes[".vcg"] = "application/vnd.groove-vcard"; //	Groove - Vcard
		mimeTypes[".hal"] = "application/vnd.hal+xml"; //	Hypertext Application Language
		mimeTypes[".zmm"] = "application/vnd.handheld-entertainment+xml"; //	ZVUE Media Manager
		mimeTypes[".hbci"] = "application/vnd.hbci"; //	Homebanking Computer Interface (HBCI)
		mimeTypes[".les"] = "application/vnd.hhe.lesson-player"; //	Archipelago Lesson Player
		mimeTypes[".hpgl"] = "application/vnd.hp-hpgl"; //	HP-GL/2 and HP RTL
		mimeTypes[".hpid"] = "application/vnd.hp-hpid"; //	Hewlett Packard Instant Delivery
		mimeTypes[".hps"] = "application/vnd.hp-hps"; //	Hewlett-Packard's WebPrintSmart
		mimeTypes[".jlt"] = "application/vnd.hp-jlyt"; //	HP Indigo Digital Press - Job Layout Languate
		mimeTypes[".pcl"] = "application/vnd.hp-pcl"; //	HP Printer Command Language
		mimeTypes[".pclxl"] = "application/vnd.hp-pclxl"; //	PCL 6 Enhanced (Formely PCL XL)
		mimeTypes[".sfd"] = "application/vnd.hydrostatix.sof-data"; //-hdstx	Hydrostatix Master Suite
		mimeTypes[".x3d"] = "application/vnd.hzn-3d-crossword"; //	3D Crossword Plugin
		mimeTypes[".mpy"] = "application/vnd.ibm.minipay"; //	MiniPay
		mimeTypes[".afp"] = "application/vnd.ibm.modcap"; //	MO:DCA-P
		mimeTypes[".irm"] = "application/vnd.ibm.rights-management"; //	IBM DB2 Rights Manager
		mimeTypes[".sc"] = "application/vnd.ibm.secure-container"; //	IBM Electronic Media Management System - Secure Container
		mimeTypes[".icc"] = "application/vnd.iccprofile"; //	ICC profile
		mimeTypes[".igl"] = "application/vnd.igloader"; //	igLoader
		mimeTypes[".ivp"] = "application/vnd.immervision-ivp"; //	ImmerVision PURE Players
		mimeTypes[".ivu"] = "application/vnd.immervision-ivu"; //	ImmerVision PURE Players
		mimeTypes[".igm"] = "application/vnd.insors.igm"; //	IOCOM Visimeet
		mimeTypes[".xpw"] = "application/vnd.intercon.formnet"; //	Intercon FormNet
		mimeTypes[".i2g"] = "application/vnd.intergeo"; //	Interactive Geometry Software
		mimeTypes[".qbo"] = "application/vnd.intu.qbo"; //	Open Financial Exchange
		mimeTypes[".qfx"] = "application/vnd.intu.qfx"; //	Quicken
		mimeTypes[".rcprofile"] = "application/vnd.ipunplugged.rcprofile"; //	IP Unplugged Roaming Client
		mimeTypes[".irp"] = "application/vnd.irepository.package+xml"; //	iRepository / Lucidoc Editor
		mimeTypes[".xpr"] = "application/vnd.is-xpr"; //	Express by Infoseek
		mimeTypes[".fcs"] = "application/vnd.isac.fcs"; //	International Society for Advancement of Cytometry
		mimeTypes[".jam"] = "application/vnd.jam"; //	Lightspeed Audio Lab
		mimeTypes[".rms"] = "application/vnd.jcp.javame.midlet-rms"; //	Mobile Information Device Profile
		mimeTypes[".jisp"] = "application/vnd.jisp"; //	RhymBox
		mimeTypes[".joda"] = "application/vnd.joost.joda-archive"; //	Joda Archive
		mimeTypes[".ktz"] = "application/vnd.kahootz"; //	Kahootz
		mimeTypes[".karbon"] = "application/vnd.kde.karbon"; //	KDE KOffice Office Suite - Karbon
		mimeTypes[".chrt"] = "application/vnd.kde.kchart"; //	KDE KOffice Office Suite - KChart
		mimeTypes[".kfo"] = "application/vnd.kde.kformula"; //	KDE KOffice Office Suite - Kformula
		mimeTypes[".flw"] = "application/vnd.kde.kivio"; //	KDE KOffice Office Suite - Kivio
		mimeTypes[".kon"] = "application/vnd.kde.kontour"; //	KDE KOffice Office Suite - Kontour
		mimeTypes[".kpr"] = "application/vnd.kde.kpresenter"; //	KDE KOffice Office Suite - Kpresenter
		mimeTypes[".ksp"] = "application/vnd.kde.kspread"; //	KDE KOffice Office Suite - Kspread
		mimeTypes[".kwd"] = "application/vnd.kde.kword"; //	KDE KOffice Office Suite - Kword
		mimeTypes[".htke"] = "application/vnd.kenameaapp"; //	Kenamea App
		mimeTypes[".kia"] = "application/vnd.kidspiration"; //	Kidspiration
		mimeTypes[".kne"] = "application/vnd.kinar"; //	Kinar Applications
		mimeTypes[".skp"] = "application/vnd.koan"; //	SSEYO Koan Play File
		mimeTypes[".sse"] = "application/vnd.kodak-descriptor"; //	Kodak Storyshare
		mimeTypes[".lasxml"] = "application/vnd.las.las+xml"; //	Laser App Enterprise
		mimeTypes[".lbd"] = "application/vnd.llamagraphics.life-balance.desktop"; //	Life Balance - Desktop Edition
		mimeTypes[".lbe"] = "application/vnd.llamagraphics.life-balance.exchange+xml"; //	Life Balance - Exchange Format
		mimeTypes[".apr"] = "application/vnd.lotus-approach"; //	Lotus Approach
		mimeTypes[".pre"] = "application/vnd.lotus-freelance"; //	Lotus Freelance
		mimeTypes[".nsf"] = "application/vnd.lotus-notes"; //	Lotus Notes
		mimeTypes[".org"] = "application/vnd.lotus-organizer"; //	Lotus Organizer
		mimeTypes[".scm"] = "application/vnd.lotus-screencam"; //	Lotus Screencam
		mimeTypes[".lwp"] = "application/vnd.lotus-wordpro"; //	Lotus Wordpro
		mimeTypes[".portpkg"] = "application/vnd.macports.portpkg"; //	MacPorts Port System
		mimeTypes[".mcd"] = "application/vnd.mcd"; //	Micro CADAM Helix D&D
		mimeTypes[".mc1"] = "application/vnd.medcalcdata"; //	MedCalc
		mimeTypes[".cdkey"] = "application/vnd.mediastation.cdkey"; //	MediaRemote
		mimeTypes[".mwf"] = "application/vnd.mfer"; //	Medical Waveform Encoding Format
		mimeTypes[".mfm"] = "application/vnd.mfmp"; //	Melody Format for Mobile Platform
		mimeTypes[".flo"] = "application/vnd.micrografx.flo"; //	Micrografx
		mimeTypes[".igx"] = "application/vnd.micrografx.igx"; //	Micrografx iGrafx Professional
		mimeTypes[".mif"] = "application/vnd.mif"; //	FrameMaker Interchange Format
		mimeTypes[".daf"] = "application/vnd.mobius.daf"; //	Mobius Management Systems - UniversalArchive
		mimeTypes[".dis"] = "application/vnd.mobius.dis"; //	Mobius Management Systems - Distribution Database
		mimeTypes[".mbk"] = "application/vnd.mobius.mbk"; //	Mobius Management Systems - Basket file
		mimeTypes[".mqy"] = "application/vnd.mobius.mqy"; //	Mobius Management Systems - Query File
		mimeTypes[".msl"] = "application/vnd.mobius.msl"; //	Mobius Management Systems - Script Language
		mimeTypes[".plc"] = "application/vnd.mobius.plc"; //	Mobius Management Systems - Policy Definition Language File
		mimeTypes[".txf"] = "application/vnd.mobius.txf"; //	Mobius Management Systems - Topic Index File
		mimeTypes[".mpn"] = "application/vnd.mophun.application"; //	Mophun VM
		mimeTypes[".mpc"] = "application/vnd.mophun.certificate"; //	Mophun Certificate
		mimeTypes[".xul"] = "application/vnd.mozilla.xul+xml"; //	XUL - XML User Interface Language
		mimeTypes[".cil"] = "application/vnd.ms-artgalry"; //	Microsoft Artgalry
		mimeTypes[".cab"] = "application/vnd.ms-cab-compressed"; //	Microsoft Cabinet File
		mimeTypes[".xls"] = "application/vnd.ms-excel"; //	Microsoft Excel
		mimeTypes[".xlam"] ="application/vnd.ms-excel.addin.macroenabled.12"; //	Microsoft Excel - Add-In File
		mimeTypes[".xlsb"] = "application/vnd.ms-excel.sheet.binary.macroenabled.12"; //	Microsoft Excel - Binary Workbook
		mimeTypes[".xlsm"] = "application/vnd.ms-excel.sheet.macroenabled.12"; //	Microsoft Excel - Macro-Enabled Workbook
		mimeTypes[".xltm"] = "application/vnd.ms-excel.template.macroenabled.12"; //	Microsoft Excel - Macro-Enabled Template File
		mimeTypes[".eot"] = "application/vnd.ms-fontobject"; //	Microsoft Embedded OpenType
		mimeTypes[".chm"] = "application/vnd.ms-htmlhelp"; //	Microsoft Html Help File
		mimeTypes[".ims"] = "application/vnd.ms-ims"; //	Microsoft Class Server
		mimeTypes[".lrm"] = "application/vnd.ms-lrm"; //	Microsoft Learning Resource Module
		mimeTypes[".thmx"] = "application/vnd.ms-officetheme"; //	Microsoft Office System Release Theme
		mimeTypes[".cat"] = "application/vnd.ms-pki.seccat"; //	Microsoft Trust UI Provider - Security Catalog
		mimeTypes[".stl"] = "application/vnd.ms-pki.stl"; //	Microsoft Trust UI Provider - Certificate Trust Link
		mimeTypes[".ppt"] = "application/vnd.ms-powerpoint"; //	Microsoft PowerPoint
		mimeTypes[".ppam"] = "application/vnd.ms-powerpoint.addin.macroenabled.12"; //	Microsoft PowerPoint - Add-in file
		mimeTypes[".pptm"] = "application/vnd.ms-powerpoint.presentation.macroenabled.12"; //	Microsoft PowerPoint - Macro-Enabled Presentation File
		mimeTypes[".sldm"] = "application/vnd.ms-powerpoint.slide.macroenabled.12"; //	Microsoft PowerPoint - Macro-Enabled Open XML Slide
		mimeTypes[".ppsm"] = "application/vnd.ms-powerpoint.slideshow.macroenabled.12"; //	Microsoft PowerPoint - Macro-Enabled Slide Show File
		mimeTypes[".potm"] = "application/vnd.ms-powerpoint.template.macroenabled.12"; //	Microsoft PowerPoint - Macro-Enabled Template File
		mimeTypes[".mpp"] = "application/vnd.ms-project"; //	Microsoft Project
		mimeTypes[".docm"] = "application/vnd.ms-word.document.macroenabled.12"; //	Microsoft Word - Macro-Enabled Document
		mimeTypes[".dotm"] = "application/vnd.ms-word.template.macroenabled.12"; //	Microsoft Word - Macro-Enabled Template
		mimeTypes[".wps"] = "application/vnd.ms-works"; //	Microsoft Works
		mimeTypes[".wpl"] = "application/vnd.ms-wpl"; //	Microsoft Windows Media Player Playlist
		mimeTypes[".xps"] = "application/vnd.ms-xpsdocument"; //	Microsoft XML Paper Specification
		mimeTypes[".mseq"] = "application/vnd.mseq"; //	3GPP MSEQ File
		mimeTypes[".mus"] = "application/vnd.musician"; //	MUsical Score Interpreted Code Invented for the ASCII designation of Notation
		mimeTypes[".msty"] = "application/vnd.muvee.style"; //	Muvee Automatic Video Editing
		mimeTypes[".nlu"] = "application/vnd.neurolanguage.nlu"; //	neuroLanguage
		mimeTypes[".nnd"] = "application/vnd.noblenet-directory"; //	NobleNet Directory
		mimeTypes[".nns"] = "application/vnd.noblenet-sealer"; //	NobleNet Sealer
		mimeTypes[".nnw"] = "application/vnd.noblenet-web"; //	NobleNet Web
		mimeTypes[".ngdat"] = "application/vnd.nokia.n-gage.data"; //	N-Gage Game Data
		mimeTypes[".n"] = "application/vnd.nokia.n-gage.symbian.install"; //-gage	N-Gage Game Installer
		mimeTypes[".rpst"] = "application/vnd.nokia.radio-preset"; //	Nokia Radio Application - Preset
		mimeTypes[".rpss"] = "application/vnd.nokia.radio-presets"; //	Nokia Radio Application - Preset
		mimeTypes[".edm"] = "application/vnd.novadigm.edm"; //	Novadigm's RADIA and EDM products
		mimeTypes[".edx"] = "application/vnd.novadigm.edx"; //	Novadigm's RADIA and EDM products
		mimeTypes[".ext"] = "application/vnd.novadigm.ext"; //	Novadigm's RADIA and EDM products
		mimeTypes[".odc"] = "application/vnd.oasis.opendocument.chart"; //	OpenDocument Chart
		mimeTypes[".otc"] = "application/vnd.oasis.opendocument.chart-template"; //	OpenDocument Chart Template
		mimeTypes[".odb"] = "application/vnd.oasis.opendocument.database"; //	OpenDocument Database
		mimeTypes[".odf"] = "application/vnd.oasis.opendocument.formula"; //	OpenDocument Formula
		mimeTypes[".odft"] = "application/vnd.oasis.opendocument.formula-template"; //	OpenDocument Formula Template
		mimeTypes[".odg"] = "application/vnd.oasis.opendocument.graphics"; //	OpenDocument Graphics
		mimeTypes[".otg"] = "application/vnd.oasis.opendocument.graphics-template"; //	OpenDocument Graphics Template
		mimeTypes[".odi"] = "application/vnd.oasis.opendocument.image"; //	OpenDocument Image
		mimeTypes[".oti"] = "application/vnd.oasis.opendocument.image-template"; //	OpenDocument Image Template
		mimeTypes[".odp"] = "application/vnd.oasis.opendocument.presentation"; //	OpenDocument Presentation
		mimeTypes[".otp"] = "application/vnd.oasis.opendocument.presentation-template"; //	OpenDocument Presentation Template
		mimeTypes[".ods"] = "application/vnd.oasis.opendocument.spreadsheet"; //	OpenDocument Spreadsheet
		mimeTypes[".ots"] = "application/vnd.oasis.opendocument.spreadsheet-template"; //	OpenDocument Spreadsheet Template
		mimeTypes[".odt"] = "application/vnd.oasis.opendocument.text"; //	OpenDocument Text
		mimeTypes[".odm"] = "application/vnd.oasis.opendocument.text-master"; //	OpenDocument Text Master
		mimeTypes[".ott"] = "application/vnd.oasis.opendocument.text-template"; //	OpenDocument Text Template
		mimeTypes[".oth"] = "application/vnd.oasis.opendocument.text-web"; //	Open Document Text Web
		mimeTypes[".xo"] = "application/vnd.olpc-sugar"; //	Sugar Linux Application Bundle
		mimeTypes[".dd2"] = "application/vnd.oma.dd2+xml"; //	OMA Download Agents
		mimeTypes[".oxt"] = "application/vnd.openofficeorg.extension"; //	Open Office Extension
		mimeTypes[".pptx"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation"; //	Microsoft Office - OOXML - Presentation
		mimeTypes[".sldx"] = "application/vnd.openxmlformats-officedocument.presentationml.slide"; //	Microsoft Office - OOXML - Presentation (Slide)
		mimeTypes[".ppsx"] = "application/vnd.openxmlformats-officedocument.presentationml.slideshow"; //	Microsoft Office - OOXML - Presentation (Slideshow)
		mimeTypes[".potx"] = "application/vnd.openxmlformats-officedocument.presentationml.template"; //	Microsoft Office - OOXML - Presentation Template
		mimeTypes[".xlsx"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"; //	Microsoft Office - OOXML - Spreadsheet
		mimeTypes[".xltx"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.template"; //	Microsoft Office - OOXML - Spreadsheet Template
		mimeTypes[".docx"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"; //	Microsoft Office - OOXML - Word Document
		mimeTypes[".dotx"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.template"; //	Microsoft Office - OOXML - Word Document Template
		mimeTypes[".mgp"] = "application/vnd.osgeo.mapguide.package"; //	MapGuide DBXML
		mimeTypes[".dp"] = "application/vnd.osgi.dp"; //	OSGi Deployment Package
		mimeTypes[".pdb"] = "application/vnd.palm"; //	PalmOS Data
		mimeTypes[".paw"] = "application/vnd.pawaafile"; //	PawaaFILE
		mimeTypes[".str"] = "application/vnd.pg.format"; //	Proprietary P&G Standard Reporting System
		mimeTypes[".ei6"] = "application/vnd.pg.osasli"; //	Proprietary P&G Standard Reporting System
		mimeTypes[".efif"] = "application/vnd.picsel"; //	Pcsel eFIF File
		mimeTypes[".wg"] = "application/vnd.pmi.widget"; //	Qualcomm's Plaza Mobile Internet
		mimeTypes[".plf"] = "application/vnd.pocketlearn"; //	PocketLearn Viewers
		mimeTypes[".pbd"] = "application/vnd.powerbuilder6"; //	PowerBuilder
		mimeTypes[".box"] = "application/vnd.previewsystems.box"; //	Preview Systems ZipLock/VBox
		mimeTypes[".mgz"] = "application/vnd.proteus.magazine"; //	EFI Proteus
		mimeTypes[".qps"] = "application/vnd.publishare-delta-tree"; //	PubliShare Objects
		mimeTypes[".ptid"] = "application/vnd.pvi.ptid1"; //	Princeton Video Image
		mimeTypes[".qxd"] = "application/vnd.quark.quarkxpress"; //	QuarkXpress
		mimeTypes[".bed"] = "application/vnd.realvnc.bed"; //	RealVNC
		mimeTypes[".mxl"] = "application/vnd.recordare.musicxml"; //	Recordare Applications
		mimeTypes[".musicxml"] = "application/vnd.recordare.musicxml+xml"; //	Recordare Applications
		mimeTypes[".cryptonote"] = "application/vnd.rig.cryptonote"; //	CryptoNote
		mimeTypes[".cod"] = "application/vnd.rim.cod"; //	Blackberry COD File
		mimeTypes[".rm"] = "application/vnd.rn-realmedia"; //	RealMedia
		mimeTypes[".link66"] = "application/vnd.route66.link66+xml"; //	ROUTE 66 Location Based Services
		mimeTypes[".st"] = "application/vnd.sailingtracker.track"; //	SailingTracker
		mimeTypes[".see"] = "application/vnd.seemail"; //	SeeMail
		mimeTypes[".sema"] = "application/vnd.sema"; //	Secured eMail
		mimeTypes[".semd"] = "application/vnd.semd"; //	Secured eMail
		mimeTypes[".semf"] = "application/vnd.semf"; //	Secured eMail
		mimeTypes[".ifm"] = "application/vnd.shana.informed.formdata"; //	Shana Informed Filler
		mimeTypes[".itp"] = "application/vnd.shana.informed.formtemplate"; //	Shana Informed Filler
		mimeTypes[".iif"] = "application/vnd.shana.informed.interchange"; //	Shana Informed Filler
		mimeTypes[".ipk"] = "application/vnd.shana.informed.package"; //	Shana Informed Filler
		mimeTypes[".twd"] = "application/vnd.simtech-mindmapper"; //	SimTech MindMapper
		mimeTypes[".mmf"] = "application/vnd.smaf"; //	SMAF File
		mimeTypes[".teacher"] = "application/vnd.smart.teacher"; //	SMART Technologies Apps
		mimeTypes[".sdkm"] = "application/vnd.solent.sdkm+xml"; //	SudokuMagic
		mimeTypes[".dxp"] = "application/vnd.spotfire.dxp"; //	TIBCO Spotfire
		mimeTypes[".sfs"] = "application/vnd.spotfire.sfs"; //	TIBCO Spotfire
		mimeTypes[".sdc"] = "application/vnd.stardivision.calc"; //	StarOffice - Calc
		mimeTypes[".sda"] = "application/vnd.stardivision.draw"; //	StarOffice - Draw
		mimeTypes[".sdd"] = "application/vnd.stardivision.impress"; //	StarOffice - Impress
		mimeTypes[".smf"] = "application/vnd.stardivision.math"; //	StarOffice - Math
		mimeTypes[".sdw"] = "application/vnd.stardivision.writer"; //	StarOffice - Writer
		mimeTypes[".sgl"] = "application/vnd.stardivision.writer-global"; //	StarOffice - Writer (Global)
		mimeTypes[".sm"] = "application/vnd.stepmania.stepchart"; //	StepMania
		mimeTypes[".sxc"] = "application/vnd.sun.xml.calc"; //	OpenOffice - Calc (Spreadsheet)
		mimeTypes[".stc"] = "application/vnd.sun.xml.calc.template"; //	OpenOffice - Calc Template (Spreadsheet)
		mimeTypes[".sxd"] = "application/vnd.sun.xml.draw"; //	OpenOffice - Draw (Graphics)
		mimeTypes[".std"] = "application/vnd.sun.xml.draw.template"; //	OpenOffice - Draw Template (Graphics)
		mimeTypes[".sxi"] = "application/vnd.sun.xml.impress"; //	OpenOffice - Impress (Presentation)
		mimeTypes[".sti"] = "application/vnd.sun.xml.impress.template"; //	OpenOffice - Impress Template (Presentation)
		mimeTypes[".sxm"] = "application/vnd.sun.xml.math"; //	OpenOffice - Math (Formula)
		mimeTypes[".sxw"] = "application/vnd.sun.xml.writer"; //	OpenOffice - Writer (Text - HTML)
		mimeTypes[".sxg"] = "application/vnd.sun.xml.writer.global"; //	OpenOffice - Writer (Text - HTML)
		mimeTypes[".stw"] = "application/vnd.sun.xml.writer.template"; //	OpenOffice - Writer Template (Text - HTML)
		mimeTypes[".sus"] = "application/vnd.sus-calendar"; //	ScheduleUs
		mimeTypes[".svd"] = "application/vnd.svd"; //	SourceView Document
		mimeTypes[".sis"] = "application/vnd.symbian.install"; //	Symbian Install Package
		mimeTypes[".bdm"] = "application/vnd.syncml.dm+wbxml"; //	SyncML - Device Management
		mimeTypes[".xdm"] = "application/vnd.syncml.dm+xml"; //	SyncML - Device Management
		mimeTypes[".xsm"] = "application/vnd.syncml+xml"; //	SyncML
		mimeTypes[".tao"] = "application/vnd.tao.intent-module-archive"; //	Tao Intent
		mimeTypes[".tmo"] = "application/vnd.tmobile-livetv"; //	MobileTV
		mimeTypes[".tpt"] = "application/vnd.trid.tpt"; //	TRI Systems Config
		mimeTypes[".mxs"] = "application/vnd.triscape.mxs"; //	Triscape Map Explorer
		mimeTypes[".tra"] = "application/vnd.trueapp"; //	True BASIC
		mimeTypes[".ufd"] = "application/vnd.ufdl"; //	Universal Forms Description Language
		mimeTypes[".utz"] = "application/vnd.uiq.theme"; //	User Interface Quartz - Theme (Symbian)
		mimeTypes[".umj"] = "application/vnd.umajin"; //	UMAJIN
		mimeTypes[".unityweb"] = "application/vnd.unity"; //	Unity 3d
		mimeTypes[".uoml"] = "application/vnd.uoml+xml"; //	Unique Object Markup Language
		mimeTypes[".vcx"] = "application/vnd.vcx"; //	VirtualCatalog
		mimeTypes[".vsd"] = "application/vnd.visio"; //	Microsoft Visio
		mimeTypes[".vsdx"] = "application/vnd.visio2013"; //	Microsoft Visio 2013
		mimeTypes[".vis"] = "application/vnd.visionary"; //	Visionary
		mimeTypes[".vsf"] = "application/vnd.vsf"; //	Viewport+
		mimeTypes[".wbxml"] = "application/vnd.wap.wbxml"; //	WAP Binary XML (WBXML)
		mimeTypes[".wmlc"] = "application/vnd.wap.wmlc"; //	Compiled Wireless Markup Language (WMLC)
		mimeTypes[".wmlsc"] = "application/vnd.wap.wmlscriptc"; //	WMLScript
		mimeTypes[".wtb"] = "application/vnd.webturbo"; //	WebTurbo
		mimeTypes[".nbp"] = "application/vnd.wolfram.player"; //	Mathematica Notebook Player
		mimeTypes[".wpd"] = "application/vnd.wordperfect"; //	Wordperfect
		mimeTypes[".wqd"] = "application/vnd.wqd"; //	SundaHus WQ
		mimeTypes[".stf"] = "application/vnd.wt.stf"; //	Worldtalk
		mimeTypes[".xar"] = "application/vnd.xara"; //	CorelXARA
		mimeTypes[".xfdl"] = "application/vnd.xfdl"; //	Extensible Forms Description Language
		mimeTypes[".hvd"] = "application/vnd.yamaha.hv-dic"; //	HV Voice Dictionary
		mimeTypes[".hvs"] = "application/vnd.yamaha.hv-script"; //	HV Script
		mimeTypes[".hvp"] = "application/vnd.yamaha.hv-voice"; //	HV Voice Parameter
		mimeTypes[".osf"] = "application/vnd.yamaha.openscoreformat"; //	Open Score Format
		mimeTypes[".osfpvg"] = "application/vnd.yamaha.openscoreformat.osfpvg+xml"; //	OSFPVG
		mimeTypes[".saf"] = "application/vnd.yamaha.smaf-audio"; //	SMAF Audio
		mimeTypes[".spf"] = "application/vnd.yamaha.smaf-phrase"; //	SMAF Phrase
		mimeTypes[".cmp"] = "application/vnd.yellowriver-custom-menu"; //	CustomMenu
		mimeTypes[".zir"] = "application/vnd.zul"; //	Z.U.L. Geometry
		mimeTypes[".zaz"] = "application/vnd.zzazz.deck+xml"; //	Zzazz Deck
		mimeTypes[".vxml"] = "application/voicexml+xml"; //	VoiceXML
		mimeTypes[".wgt"] = "application/widget"; //	Widget Packaging and XML Configuration
		mimeTypes[".hlp"] = "application/winhlp"; //	WinHelp
		mimeTypes[".wsdl"] = "application/wsdl+xml"; //	WSDL - Web Services Description Language
		mimeTypes[".wspolicy"] = "application/wspolicy+xml"; //	Web Services Policy
		mimeTypes[".7"] = "application/x-7z-compressed"; //z	7-Zip
		mimeTypes[".abw"] = "application/x-abiword"; //	AbiWord
		mimeTypes[".ace"] = "application/x-ace-compressed"; //	Ace Archive
		mimeTypes[".dmg"] = "application/x-apple-diskimage"; //	Apple Disk Image
		mimeTypes[".aab"] = "application/x-authorware-bin"; //	Adobe (Macropedia) Authorware - Binary File
		mimeTypes[".aam"] = "application/x-authorware-map"; //	Adobe (Macropedia) Authorware - Map
		mimeTypes[".aas"] = "application/x-authorware-seg"; //	Adobe (Macropedia) Authorware - Segment File
		mimeTypes[".bcpio"] = "application/x-bcpio"; //	Binary CPIO Archive
		mimeTypes[".torrent"] = "application/x-bittorrent"; //	BitTorrent
		mimeTypes[".bz"] = "application/x-bzip"; //	Bzip Archive
		mimeTypes[".bz2"] = "application/x-bzip2"; //	Bzip2 Archive
		mimeTypes[".vcd"] = "application/x-cdlink"; //	Video CD
		mimeTypes[".chat"] = "application/x-chat"; //	pIRCh
		mimeTypes[".pgn"] = "application/x-chess-pgn"; //	Portable Game Notation (Chess Games)
		mimeTypes[".cpio"] = "application/x-cpio"; //	CPIO Archive
		mimeTypes[".csh"] = "application/x-csh"; //	C Shell Script
		mimeTypes[".deb"] = "application/x-debian-package"; //	Debian Package
		mimeTypes[".dir"] = "application/x-director"; //	Adobe Shockwave Player
		mimeTypes[".wad"] = "application/x-doom"; //	Doom Video Game
		mimeTypes[".ncx"] = "application/x-dtbncx+xml"; //	Navigation Control file for XML (for ePub)
		mimeTypes[".dtb"] = "application/x-dtbook+xml"; //	Digital Talking Book
		mimeTypes[".res"] = "application/x-dtbresource+xml"; //	Digital Talking Book - Resource File
		mimeTypes[".dvi"] = "application/x-dvi"; //	Device Independent File Format (DVI)
		mimeTypes[".bdf"] = "application/x-font-bdf"; //	Glyph Bitmap Distribution Format
		mimeTypes[".gsf"] = "application/x-font-ghostscript"; //	Ghostscript Font
		mimeTypes[".psf"] = "application/x-font-linux-psf"; //	PSF Fonts
		mimeTypes[".otf"] = "application/x-font-otf"; //	OpenType Font File
		mimeTypes[".pcf"] = "application/x-font-pcf"; //	Portable Compiled Format
		mimeTypes[".snf"] = "application/x-font-snf"; //	Server Normal Format
		mimeTypes[".ttf"] = "application/x-font-ttf"; //	TrueType Font
		mimeTypes[".pfa"] = "application/x-font-type1"; //	PostScript Fonts
		mimeTypes[".woff"] = "application/x-font-woff"; //	Web Open Font Format
		mimeTypes[".spl"] = "application/x-futuresplash"; //	FutureSplash Animator
		mimeTypes[".gnumeric"] = "application/x-gnumeric"; //	Gnumeric
		mimeTypes[".gtar"] = "application/x-gtar"; //	GNU Tar Files
		mimeTypes[".hdf"] = "application/x-hdf"; //	Hierarchical Data Format
		mimeTypes[".jnlp"] = "application/x-java-jnlp-file"; //	Java Network Launching Protocol
		mimeTypes[".latex"] = "application/x-latex"; //	LaTeX
		mimeTypes[".prc"] = "application/x-mobipocket-ebook"; //	Mobipocket
		mimeTypes[".application"] = "application/x-ms-application"; //	Microsoft ClickOnce
		mimeTypes[".wmd"] = "application/x-ms-wmd"; //	Microsoft Windows Media Player Download Package
		mimeTypes[".wmz"] = "application/x-ms-wmz"; //	Microsoft Windows Media Player Skin Package
		mimeTypes[".xbap"] = "application/x-ms-xbap"; //	Microsoft XAML Browser Application
		mimeTypes[".mdb"] = "application/x-msaccess"; //	Microsoft Access
		mimeTypes[".obd"] = "application/x-msbinder"; //	Microsoft Office Binder
		mimeTypes[".crd"] = "application/x-mscardfile"; //	Microsoft Information Card
		mimeTypes[".clp"] = "application/x-msclip"; //	Microsoft Clipboard Clip
		mimeTypes[".exe"] = "application/x-msdownload"; //	Microsoft Application
		mimeTypes[".mvb"] = "application/x-msmediaview"; //	Microsoft MediaView
		mimeTypes[".wmf"] = "application/x-msmetafile"; //	Microsoft Windows Metafile
		mimeTypes[".mny"] = "application/x-msmoney"; //	Microsoft Money
		mimeTypes[".pub"] = "application/x-mspublisher"; //	Microsoft Publisher
		mimeTypes[".scd"] = "application/x-msschedule"; //	Microsoft Schedule+
		mimeTypes[".trm"] = "application/x-msterminal"; //	Microsoft Windows Terminal Services
		mimeTypes[".wri"] = "application/x-mswrite"; //	Microsoft Wordpad
		mimeTypes[".nc"] = "application/x-netcdf"; //	Network Common Data Form (NetCDF)
		mimeTypes[".p12"] = "application/x-pkcs12"; //	PKCS #12 - Personal Information Exchange Syntax Standard
		mimeTypes[".p7b"] = "application/x-pkcs7-certificates"; //	PKCS #7 - Cryptographic Message Syntax Standard (Certificates)
		mimeTypes[".p7r"] = "application/x-pkcs7-certreqresp"; //	PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request king_Response)
		mimeTypes[".rar"] = "application/x-rar-compressed"; //	RAR Archive
		mimeTypes[".sh"] = "application/x-sh"; //	Bourne Shell Script
		mimeTypes[".shar"] = "application/x-shar"; //	Shell Archive
		mimeTypes[".swf"] = "application/x-shockwave-flash"; //	Adobe Flash
		mimeTypes[".xap"] = "application/x-silverlight-app"; //	Microsoft Silverlight
		mimeTypes[".sit"] = "application/x-stuffit"; //	Stuffit Archive
		mimeTypes[".sitx"] = "application/x-stuffitx"; //	Stuffit Archive
		mimeTypes[".sv4cpio"] = "application/x-sv4cpio"; //	System V Release 4 CPIO Archive
		mimeTypes[".sv4crc"] = "application/x-sv4crc"; //	System V Release 4 CPIO Checksum Data
		mimeTypes[".tar"] = "application/x-tar"; //	Tar File (Tape Archive)
		mimeTypes[".tcl"] = "application/x-tcl"; //	Tcl Script
		mimeTypes[".tex"] = "application/x-tex"; //	TeX
		mimeTypes[".tfm"] = "application/x-tex-tfm"; //	TeX Font Metric
		mimeTypes[".texinfo"] = "application/x-texinfo"; //	GNU Texinfo Document
		mimeTypes[".ustar"] = "application/x-ustar"; //	Ustar (Uniform Standard Tape Archive)
		mimeTypes[".src"] = "application/x-wais-source"; //	WAIS Source
		mimeTypes[".der"] = "application/x-x509-ca-cert"; //	X.509 Certificate
		mimeTypes[".fig"] = "application/x-xfig"; //	Xfig
		mimeTypes[".xpi"] = "application/x-xpinstall"; //	XPInstall - Mozilla
		mimeTypes[".xdf"] = "application/xcap-diff+xml"; //	XML Configuration Access Protocol - XCAP Diff
		mimeTypes[".xenc"] = "application/xenc+xml"; //	XML Encryption Syntax and Processing
		mimeTypes[".xhtml"] = "application/xhtml+xml"; //	XHTML - The Extensible HyperText Markup Language
		mimeTypes[".xml"] = "application/xml"; //	XML - Extensible Markup Language
		mimeTypes[".dtd"] = "application/xml-dtd"; //	Document Type Definition
		mimeTypes[".xop"] = "application/xop+xml"; //	XML-Binary Optimized Packaging
		mimeTypes[".xslt"] = "application/xslt+xml"; //	XML Transformations
		mimeTypes[".xspf"] = "application/xspf+xml"; //	XSPF - XML Shareable Playlist Format
		mimeTypes[".mxml"] = "application/xv+xml"; //	MXML
		mimeTypes[".yang"] = "application/yang"; //	YANG Data Modeling Language
		mimeTypes[".yin"] = "application/yin+xml"; //	YIN (YANG - XML)
		mimeTypes[".zip"] = "application/zip"; //	Zip Archive

		mimeTypes[".cdx"] = "chemical/x-cdx"; // ChemDraw eXchange file
		mimeTypes[".cif"] = "chemical/x-cif"; // Crystallographic Interchange Format
		mimeTypes[".cmdf"] = "chemical/x-cmdf"; // CrystalMaker Data Format
		mimeTypes[".cml"] = "chemical/x-cml"; // Chemical Markup Language
		mimeTypes[".csml"] = "chemical/x-csml"; // Chemical Style Markup Language
		mimeTypes[".xyz"] = "chemical/x-xyz"; // XYZ File Format
		mimeTypes[".eml"] = "message/rfc822"; // Email Message
		mimeTypes[".igs"] = "model/iges"; // Initial Graphics Exchange Specification (IGES)
		mimeTypes[".msh"] = "model/mesh"; // Mesh Data Type
		mimeTypes[".dae"] = "model/vnd.collada+xml"; // COLLADA
		mimeTypes[".dwf"] = "model/vnd.dwf"; // Autodesk Design Web Format (DWF)
		mimeTypes[".gdl"] = "model/vnd.gdl"; // Geometric Description Language (GDL)
		mimeTypes[".gtw"] = "model/vnd.gtw"; // Gen-Trix Studio
		mimeTypes[".mts"] = "model/vnd.mts"; // Virtue MTS
		mimeTypes[".vtu"] = "model/vnd.vtu"; // Virtue VTU
		mimeTypes[".wrl"] = "model/vrml"; // Virtual Reality Modeling Language
		mimeTypes[".ice"] = "x-conference/x-cooltalk"; //
	}
	return mimeTypes;
}
